### ISSUE TITLE
include rectangle

### ISSUE THREAD

**Issue by kkmuffme** [burnpiro/puppeteer-screenshot-tester#16]
You already have a exclude rectangle option.

It would be great if the inverse would be possible too: include rectangle. Sometimes I want to compare only a specific part/rectangle of the screenshot, so it would be really helpful if I only have to define the include instead of having to exclude everything else.

**Comment by kkmuffme** [comment]
Perfect, thanks!

**Comment by burnpiro** [comment]
Resolved in [Release 1.3.0](https://github.com/burnpiro/puppeteer-screenshot-tester/releases/tag/1.3.0)
