### ISSUE TITLE
Test passes when screenshots are different

### ISSUE THREAD

**Issue by bondom** [burnpiro/puppeteer-screenshot-tester#18]
**Describe the bug**
`await tester(..)` returns true even if screenshots differ

**Please complete the following information:**
 - OS: macOS High Sierra v10.13.6
 - Node v11.5.0

**To Reproduce**
1. Just take your example and run it once, so picture is saved
2. Then change next line:
`await page.type('input[title="Search"]', 'Hello', { delay: 100 })`
to 
`await page.type('input[title="Search"]', 'something else', { delay: 100 })`
3. Run test again
Test passes

**Expected behavior**
Test shouldn't pass, screenshots are different

**Comment by bondom** [comment]
So it is problem of [Resembe.js](https://github.com/rsmbl/Resemble.js).

**Comment by burnpiro** [comment]
Could you provide two screenshots that are generated? It might not be a problem with algorithm at all. There was one problem with headless chrome which in come cases works differently than standard chrome. Especially on google.com. So if you could copy first screenshot then remove it and copy screenshot after second run we can check what's wrong.
If it's really related with Resemble then i could talk with them and solve the problem.

**Comment by bondom** [comment]
Okay, so I checked it again on Resemble website. Now it works on website. But test still passes. I attach screenshots.
![test2](https://user-images.githubusercontent.com/18090218/50689385-3976b180-1032-11e9-99ad-cced2c9fb343.png)
![test3](https://user-images.githubusercontent.com/18090218/50689388-3b407500-1032-11e9-9faa-1fd135aee4e6.png)

**Comment by burnpiro** [comment]
Could you show me how you call `ScreenshotTester()`. I've tested your case on macOS 10.14.1 (node 11.6.0) and Ubuntu 18.04 (node 10.11.0) and in both cases test is failing.

![test2](https://user-images.githubusercontent.com/3284639/50693898-45fa0a80-1030-11e9-927b-d6835166e41e.png)
![test2-new](https://user-images.githubusercontent.com/3284639/50693905-4befeb80-1030-11e9-953c-5bfed4fb2677.png)
![test2-diff](https://user-images.githubusercontent.com/3284639/50693862-2d89f000-1030-11e9-89a7-78c8cc27e34b.png)

**Comment by bondom** [comment]
I do it the same as in your example:

```
    const tester = await ScreenshotTester(0.8, false, false, [], {
      transparency: 0.5
    })
```

**Comment by burnpiro** [comment]
Could you change `threshold` to 0.1? (first parameter) 

It's like that to prevent detecting text changes :)

**Comment by bondom** [comment]
Now it works :)

**Comment by bondom** [comment]
When searching alternatives for Resemble I found [pixelmatch](https://github.com/mapbox/pixelmatch) library. Did you use it? If yes, could you please say about differences between Resemble and pixelmatch?

**Comment by burnpiro** [comment]
At the beginning there was idea to use pixelmatch but it was still quite young library in compare to Resemble. I have a plan to give it another try and change algorithm. But at this point Resemble have more features and provides clearer diff. Beside that anti aliasing works better (or at least worked better).

Right now there is no much big of a difference between two except pixelmatch being slightly faster. But if you're running tests only in major features it won't make any difference. We have one case that screenshot tester is running for about 15-20min but that's component library and it's testing every single variation of each component.
