### ISSUE TITLE
Option 'type' appears to be ignored?

### ISSUE THREAD

**Issue by densk1** [burnpiro/puppeteer-screenshot-tester#7]
Currently trying to set filetype to jpeg but it is appearing to be ignored.

```
    it(`Route / should match screenshot on -> [${deviceName}]`, async () => {
      const tester = await ScreenshotTester();
      const result = await tester(page, `screenshot.${deviceName}`, { type: 'jpeg' });
      expect(result).toBe(true);
    });
```

**Comment by burnpiro** [comment]
Reason for that is because `jpeg` doesn't have transparency option. To create diff when there is a mismatch between images we need to have that.

**Comment by densk1** [comment]
Thanks, so are my notes on the following correct? (showing defaults)
```
  path: '',
  type: '', // NOT VALID
  quality: '', // NOT VALID
  fullPage: false,
  clip: {
    x: 0,
    y: 0,
    width: 0,
    height: 0,
  },
  omitBackground: false,
  encoding: 'binary', // or 'base64
```

**Comment by burnpiro** [comment]
Yes you're right. Only thing is that `omitBackground` is ignored when generating diff (otherwise you couldn't see layers).
